name: Upload To Chrome Web Store

on:
  release:
    types: [created]

jobs:
  build:
    name: Upload
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create Release Version
        run: ./create-release-version.sh

      - name: Upload To Store
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: 'ojdofoikeplghgcomajojeinnjniecld'
          zip: release.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
